# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "MolestCPP11",
    srcs = ["cpp_molest.cpp"],
    hdrs = ["cpp_molest.h"],
    visibility = ["//:__pkg__"],
)